configure_esp_secure_cert.py \
 -p /dev/ttyUSB0 \
  --keep_ds_data_on_host \
  --efuse_key_id 1 \
  --ca-cert ca.pem \
  --device-cert client.crt \
  --private-key private.key \
  --target_chip esp32s3 \
  --secure_cert_type cust_flash_tlv \
  --configure_ds \
  --priv_key_algo RSA 2048
